In [2]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv("Advertising.csv")

In [5]:
df.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [10]:
df.drop("Unnamed: 0",inplace=True,axis=1)

In [12]:
df

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [16]:
X=df[["TV","radio","newspaper"]]

In [17]:
X

TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [19]:
X.shape

(200, 3)

In [20]:
from sklearn.preprocessing import StandardScaler

In [22]:
scalar=StandardScaler()
scaled_X=scalar.fit_transform(X)

In [23]:
scaled_X

array([[ 9.69852266e-01,  9.81522472e-01,  1.77894547e+00],
       [-1.19737623e+00,  1.08280781e+00,  6.69578760e-01],
       [-1.51615499e+00,  1.52846331e+00,  1.78354865e+00],
       [ 5.20496822e-02,  1.21785493e+00,  1.28640506e+00],
       [ 3.94182198e-01, -8.41613655e-01,  1.28180188e+00],
       [-1.61540845e+00,  1.73103399e+00,  2.04592999e+00],
       [-1.04557682e+00,  6.43904671e-01, -3.24708413e-01],
       [-3.13436589e-01, -2.47406325e-01, -8.72486994e-01],
       [-1.61657614e+00, -1.42906863e+00, -1.36042422e+00],
       [ 6.16042873e-01, -1.39530685e+00, -4.30581584e-01],
       [-9.45155670e-01, -1.17923146e+00, -2.92486143e-01],
       [ 7.90028350e-01,  4.96973404e-02, -1.22232878e+00],
       [-1.43908760e+00,  7.99208859e-01,  1.62704048e+00],
       [-5.78501712e-01, -1.05768905e+00, -1.07502697e+00],
       [ 6.66253447e-01,  6.50657027e-01,  7.11007392e-01],
       [ 5.64664612e-01,  1.65000572e+00,  1.02862691e+00],
       [-9.25304978e-01,  9.00494200e-01

In [25]:
from sklearn.decomposition import PCA

In [28]:
pca=PCA(n_components=2)

In [33]:
new_x=pca.fit_transform(scaled_X)

In [34]:
new_x

array([[ 2.11112370e+00, -5.45027210e-01],
       [ 9.63044201e-01,  1.42989496e+00],
       [ 1.97568580e+00,  1.96917371e+00],
       [ 1.74293539e+00,  3.17003564e-01],
       [ 3.86960891e-01, -3.26527566e-01],
       [ 2.27665828e+00,  2.13444167e+00],
       [ 3.17186325e-03,  1.07223024e+00],
       [-8.39906010e-01,  1.43642168e-01],
       [-2.26540773e+00,  1.17104356e+00],
       [-1.13458115e+00, -8.73539109e-01],
       [-1.21416821e+00,  7.05811852e-01],
       [-6.47171894e-01, -9.41737232e-01],
       [ 1.37921018e+00,  1.76206588e+00],
       [-1.59537526e+00,  2.52420962e-01],
       [ 1.08032202e+00, -4.51705963e-01],
       [ 1.96991938e+00, -1.56939468e-01],
       [ 3.08805064e+00,  1.59421732e+00],
       [ 1.89288215e+00, -1.20179394e+00],
       [-7.08283732e-01,  7.79755578e-01],
       [-3.34498821e-01, -7.26080430e-02],
       [ 1.10796157e+00, -6.18422481e-01],
       [-8.53343856e-01, -1.26245269e+00],
       [-6.20458387e-02,  1.58082714e+00],
       [-2.

In [35]:
pca.explained_variance_

array([1.37774122, 0.98819712])

In [36]:
pca.components_ #already Transpose

array([[ 0.20787391,  0.69139674,  0.69192412],
       [-0.97814838,  0.14965532,  0.14432267]])

# by Mathematically

In [48]:
center_x=scaled_X-scaled_X.mean()

In [49]:
center_x

array([[ 9.69852266e-01,  9.81522472e-01,  1.77894547e+00],
       [-1.19737623e+00,  1.08280781e+00,  6.69578760e-01],
       [-1.51615499e+00,  1.52846331e+00,  1.78354865e+00],
       [ 5.20496822e-02,  1.21785493e+00,  1.28640506e+00],
       [ 3.94182198e-01, -8.41613655e-01,  1.28180188e+00],
       [-1.61540845e+00,  1.73103399e+00,  2.04592999e+00],
       [-1.04557682e+00,  6.43904671e-01, -3.24708413e-01],
       [-3.13436589e-01, -2.47406325e-01, -8.72486994e-01],
       [-1.61657614e+00, -1.42906863e+00, -1.36042422e+00],
       [ 6.16042873e-01, -1.39530685e+00, -4.30581584e-01],
       [-9.45155670e-01, -1.17923146e+00, -2.92486143e-01],
       [ 7.90028350e-01,  4.96973404e-02, -1.22232878e+00],
       [-1.43908760e+00,  7.99208859e-01,  1.62704048e+00],
       [-5.78501712e-01, -1.05768905e+00, -1.07502697e+00],
       [ 6.66253447e-01,  6.50657027e-01,  7.11007392e-01],
       [ 5.64664612e-01,  1.65000572e+00,  1.02862691e+00],
       [-9.25304978e-01,  9.00494200e-01

In [52]:
center_xd=pd.DataFrame(center_x)

In [53]:
center_xd

0         1         2
0    0.969852  0.981522  1.778945
1   -1.197376  1.082808  0.669579
2   -1.516155  1.528463  1.783549
3    0.052050  1.217855  1.286405
4    0.394182 -0.841614  1.281802
..        ...       ...       ...
195 -1.270941 -1.321031 -0.771217
196 -0.617035 -1.240003 -1.033598
197  0.349810 -0.942899 -1.111852
198  1.594565  1.265121  1.640850
199  0.993206 -0.990165 -1.005979

[200 rows x 3 columns]

In [54]:
mat=center_xd.cov()

In [55]:
mat

0         1         2
0  1.005025  0.055084  0.056933
1  0.055084  1.005025  0.355883
2  0.056933  0.355883  1.005025

In [56]:
eig_value,eig_vector=np.linalg.eig(mat)

In [57]:
eig_value

array([1.37774122, 0.98819712, 0.64913704])

In [58]:
eig_vector

array([[ 0.20787391,  0.97814838, -0.0037659 ],
       [ 0.69139674, -0.14965532, -0.70680537],
       [ 0.69192412, -0.14432267,  0.70739804]])

In [59]:
X_new=np.dot(center_xd,eig_vector[:2,:].T)

In [60]:
X_new.shape

(200, 2)

In [61]:
X_new

array([[ 1.15498228e+00, -7.33705571e-01],
       [ 8.07721859e-01, -1.46317183e+00],
       [ 1.17317818e+00, -2.53762904e+00],
       [ 1.19721813e+00, -1.05550949e+00],
       [-7.46109973e-01, -5.07496211e-01],
       [ 1.34970205e+00, -2.82202088e+00],
       [ 4.13708984e-01, -5.89766510e-01],
       [-3.03869689e-01,  4.36995130e-01],
       [-1.72876196e+00,  5.77273895e-02],
       [-1.23513636e+00,  9.39082498e-01],
       [-1.34883507e+00, -2.70268517e-01],
       [ 2.17440825e-01,  1.40273410e+00],
       [ 4.76468811e-01, -2.26458728e+00],
       [-1.15078380e+00,  5.18149430e-01],
       [ 7.72258247e-01, -1.39272665e-01],
       [ 1.72745576e+00, -5.83563876e-01],
       [ 6.74004717e-01, -3.48947668e+00],
       [ 1.40071312e+00,  9.82442250e-02],
       [-3.69381118e-01, -2.01828789e-01],
       [ 4.46171652e-02,  3.68313940e-01],
       [ 4.62236182e-01, -2.12039280e-01],
       [-9.79147753e-01,  1.14254578e+00],
       [-8.14557913e-01, -1.62581467e+00],
       [-2.